services:

  server:
    image: ghcr.io/ankush109/josts-server:latest
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    restart: unless-stopped

  worker:
    image: ghcr.io/ankush109/josts-worker:latest
    env_file:
      - ./.env
    restart: unless-stopped
