import Redis from "ioredis";
import puppeteer from "puppeteer";
import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3";
import dotenv from "dotenv";
import { connectDB } from "./db/connection.js";
import Report  from "./db/models/report.js";
import path from "path";
import ejs from "ejs";
dotenv.config();

// ---- Redis ----
const redis = new Redis({
  host: process.env.REDIS_HOST,
  port: process.env.REDIS_PORT,
});

// ---- S3 ----
const s3 = new S3Client({
  region: process.env.AWS_REGION,
});

const BUCKET = process.env.AWS_S3_BUCKET;

console.log("🟢 Node PDF Worker started...");

function generateHTML() {
  return `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8" />
        <style>
          body { font-family: Arial; padding: 40px; }
          header { border-bottom: 2px solid #000; margin-bottom: 20px; }
        </style>
      </head>
      <body>
        <header>
          <h1>Jost PDF Report</h1>
        </header>
        <p>Dummy PDF generated by Node worker.</p>
      </body>
    </html>
  `;
}

async function createPdfBuffer(html) {
  const browser = await puppeteer.launch({
    headless: "new",
  });

  const page = await browser.newPage();
  await page.setContent(html, { waitUntil: "networkidle0" });

  const pdfBuffer = await page.pdf({
    format: "A4",
    printBackground: true,
  });

  await browser.close();
  return pdfBuffer;
}

async function uploadToS3(buffer, key) {
  await s3.send(
    new PutObjectCommand({
      Bucket: BUCKET,
      Key: key,
      Body: buffer,
      ContentType: "application/pdf",
    })
  );
}
function renderTemplate(templatePath, data) {
    console.log(data,"data")
    return new Promise((resolve, reject) => {
      ejs.renderFile(
        templatePath,
        data,                 // ← real data
        { async: false },        // ← options (can be {} if you want defaults)
        (err, str) => {
          if (err) reject(err);
          else resolve(str);
        }
      );
    });
  }
(async function runWorker() {
    while (true) {
      await connectDB(); 
      const [, rawJob] = await redis.brpop("pdf_jobs", 0);
      const job = JSON.parse(rawJob);
  
      const jobId = job.jobId;
      const reportId = job.reportId;
      console.log(`📄 Processing job: ${jobId}`);
  

    //   const pdfBuffer = await createPdfBuffer(html);
      const report = await Report.findById(reportId);
      console.log(`📄 Generating PDF for report: ${reportId}`);
      console.log("Report Payload:", report); // Debugging line
      const templatePath = path.join(
        process.cwd(),
        "templates",
        "safe.ejs"
      );

      const html = await renderTemplate(
        templatePath,
        report.payload
      );
      const pdfBuffer = await createPdfBuffer(html);


      const s3Key = `reports/${reportId}_${report.title}.pdf`;
      await uploadToS3(pdfBuffer, s3Key);
  
      console.log(`☁️ Uploaded to S3: s3://${BUCKET}/${s3Key}`);
  
      // 🔹 Wait for 10 seconds before updating DB
      //await new Promise((resolve) => setTimeout(resolve, 10000));
  
      await Report.findByIdAndUpdate(
        reportId,
        {
          status: "uploaded",  // <-- include here
          filePath: s3Key
        },
        { new: true } // optional, returns the updated doc
      );
      console.log(`✅ Report status updated for ${reportId}`);
    }
  })();
  